### ISSUE TITLE
Can't see any save files via OPEN option 

### ISSUE THREAD

**Issue by ChettRipley** [mcred/chrono-trigger-save-editor#24]
All my saves are in .srm file type

Nothing shows up other than folders when using "open" option

What am I doing wrong.

**Comment by mcred** [comment]
I've only used it with `.sav` files from emulator. I don't know if `.srm` is different or not, but this is where more formats could be added. 
https://github.com/mcred/chrono-trigger-save-editor/blob/ded4435922eb30da87190a0510a49121099daf20/internal/app/Editor.go#L75

**Comment by ChettRipley** [comment]
EDIT: I renamed .srm to .sav and the editor found it now...will try to use this on my game and see if it works


Maybe i mis understood the "save" term

Thought it meant save state from emulator which is .srm

**Comment by mcred** [comment]
I used this with SNES9x save files, which are `.sav` files. They are also called "Battery Saves." I'm sure most of these opinionated files comes from the emulator and being on MacOS.

**Comment by ChettRipley** [comment]
Well it worked, I just renamed .srm to .sav.... edited the file... then renamed it back to .srm

Using snes9x EX+ on android

I just changed my weapons and armor out for a chrono trigger rom hack.

**Comment by mcred** [comment]
Glad to hear it. I haven't touched this project in a while and it's missing a lot of features. Would love any feedback or help if you are willing.

**Comment by ChettRipley** [comment]
not much of a coder or that, maybe testing only 

Just came on to see what I was missing and found out. I dont have .sav files on my emulation just like save slot and .srm file so wanted to see if I could figure it out so that if anyone else finds this tool they wont have the same issue.

**Comment by mcred** [comment]
I'll work on a new version to fix this issue and let you know when it's ready. Any testing feedback is greatly appreciated.
